"use client";

import { create } from "zustand";
import type Anthropic from "@anthropic-ai/sdk";
import type { Device, Lease, MeResponse } from "@/lib/ghost/contracts";
import type { WidgetSpec } from "@/components/canvas/types";

export type Activity = "idle" | "listening" | "thinking" | "speaking" | "acting";
export type Mood =
  | "neutral"
  | "happy"
  | "curious"
  | "excited"
  | "thinking"
  | "surprised"
  | "sad"
  | "determined"
  | "mischievous"
  | "proud"
  | "sleepy";

export const MOODS: Mood[] = [
  "neutral",
  "happy",
  "curious",
  "excited",
  "thinking",
  "surprised",
  "sad",
  "determined",
  "mischievous",
  "proud",
  "sleepy",
];

export interface UiToolCall {
  id: string;
  name: string;
  args?: unknown;
  result?: unknown;
  status: "running" | "done" | "error";
}

export interface UiMessage {
  id: string;
  role: "user" | "assistant";
  text: string;
  tools: UiToolCall[];
  createdAt: number;
  /** user messages generated by UI events rather than typed/spoken */
  event?: boolean;
}

export interface TraceEntry {
  at: number;
  kind: "tool" | "event" | "error" | "payment" | "model";
  title: string;
  detail?: string;
}

interface GhostState {
  me: MeResponse | null;
  transcript: Anthropic.Beta.BetaMessageParam[];
  ui: UiMessage[];
  running: boolean;
  activity: Activity;
  mood: Mood;
  caption: { who: "user" | "polty"; text: string; interim?: boolean } | null;
  toolStatus: string | null;
  widgets: WidgetSpec[];
  focusId: string | null;
  reports: Record<string, Record<string, unknown>>;
  /** Widget the ghost is currently possessing (tether line + glow). */
  possess: { widgetId: string | null; label: string; until: number } | null;
  budget: { goal: string | null; limit_cents: number; spent_cents: number };
  devices: Record<string, Device>;
  leases: Record<string, Lease>;
  trace: TraceEntry[];
  drawer: boolean;
  handsFree: boolean;
  voiceProvider: "elevenlabs" | "browser" | "unknown";
  /** "fast" = Claude Haiku 4.5 (low latency, default for voice); "deep" = Claude Opus 5.5 (hard tasks). */
  brain: "fast" | "deep";
  error: string | null;

  set: (patch: Partial<GhostState>) => void;
  upsertWidget: (w: Omit<WidgetSpec, "createdAt"> & { createdAt?: number }) => void;
  patchWidget: (id: string, patch: Record<string, unknown>, title?: string) => boolean;
  removeWidget: (id: string) => void;
  report: (id: string, data: Record<string, unknown>) => void;
  addTrace: (e: Omit<TraceEntry, "at">) => void;
}

export const useGhost = create<GhostState>((set, get) => ({
  me: null,
  transcript: [],
  ui: [],
  running: false,
  activity: "idle",
  mood: "neutral",
  caption: null,
  toolStatus: null,
  widgets: [],
  focusId: null,
  reports: {},
  possess: null,
  budget: { goal: null, limit_cents: 100, spent_cents: 0 },
  devices: {},
  leases: {},
  trace: [],
  drawer: false,
  handsFree: false,
  voiceProvider: "unknown",
  brain: "fast",
  error: null,

  set: (patch) => set(patch),
  upsertWidget: (w) => {
    const widgets = get().widgets;
    const i = widgets.findIndex((x) => x.id === w.id);
    if (i >= 0) {
      const next = widgets.slice();
      next[i] = { ...widgets[i], ...w, createdAt: widgets[i].createdAt } as WidgetSpec;
      set({ widgets: next });
    } else {
      set({ widgets: [...widgets, { ...w, createdAt: w.createdAt ?? Date.now() } as WidgetSpec] });
    }
  },
  patchWidget: (id, patch, title) => {
    const widgets = get().widgets;
    const i = widgets.findIndex((x) => x.id === id);
    if (i < 0) return false;
    const next = widgets.slice();
    next[i] = { ...widgets[i], title: title ?? widgets[i].title, props: { ...widgets[i].props, ...patch } };
    set({ widgets: next });
    return true;
  },
  removeWidget: (id) => {
    const s = get();
    const reports = { ...s.reports };
    delete reports[id];
    set({
      widgets: s.widgets.filter((w) => w.id !== id),
      focusId: s.focusId === id ? null : s.focusId,
      reports,
    });
  },
  report: (id, data) => set({ reports: { ...get().reports, [id]: { ...data, reported_at: Date.now() } } }),
  addTrace: (e) => set({ trace: [...get().trace.slice(-199), { ...e, at: Date.now() }] }),
}));

/**
 * High-frequency audio levels live outside React state (read by the mascot every frame).
 */
export const levels = { speech: 0, mic: 0 };
